import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import "@/styles/globals.css"
import { Poppins as FontSans } from "next/font/google"
import { Toaster } from "react-hot-toast";

import { cn } from "@/lib/utils"
import { Session } from "inspector";
import { SessionProvider } from "next-auth/react";
import Provider from "@/components/Provider";
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight : ["300","400","500"]
});
 

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: process.env.APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' text-foreground'}>
      <Toaster position="top-right" toastOptions={{
          success:{
            style:{
              backgroundColor:'#fff',
              border:'1px solid gray',
              borderRadius:'5px'
            },
            icon: undefined,
            iconTheme:{
              primary:'#444',
              secondary:'#fff'
            }
          },
          error:{
            style:{
              backgroundColor:'#fff',
              border:'1px solid gray',
              borderRadius:'5px',
              height:'40px',
              fontSize:'12px'
            },
            icon: undefined,
            iconTheme:{
              primary:'#444',
              secondary:'#fff'
            }
          }
        }} />
      <Provider>

      {children}
      </Provider>

        </body>
    </html>
  );
}
